version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:2.2.0
    ports:
      - "8848:8848"
  kafka:
    image: redpandadata/redpanda:v23.1.8
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
    ports:
      - "9092:9092"
      - "9644:9644"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
  gateway-ws:
    build: ../gateway-ws
    ports:
      - "8080:8080"
    depends_on:
      - kafka
  match-shard:
    build: ../match-shard
    ports:
      - "8081:8081"
      - "9090:9090"
    depends_on:
      - kafka
  profile-service:
    build: ../profile-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
  allocator-service:
    build: ../allocator-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
  notifier-service:
    build: ../notifier-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
  audit-service:
    build: ../audit-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
