server:
  port: 8848
match:
  bucket-size: 10
  max-score: 10000
  expected-load-per-bucket: 50000

  max-retries: 1
  initial-backoff: 100ms
  max-concurrent-notifications: 12000

  notifier-threads: 12
  notifier-queue-size: 13000


  max-backpressure-buffer: 9000
  sink-buffer-size: 11600


