server:
  port: 8081
spring:
  application:
    name: match-shard
  profiles:
    active: kafka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true
